#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "    _                     ___        "
echo "   /_\  ___ _ __ ___     / _ \ ___   "
echo "  / _ \/ _ \ '__/ _ \   | | | / __|  "
echo " / ___ \  __/ | | (_) |  | |_| \__ \  "
echo "/_/   \_\___|_|  \___/    \___/|___/  "
echo "                                     "
echo "========================================================"
echo "        AeroOs v2.0.0 (Internet & Wi-Fi Edition)        "
echo "========================================================"
echo "[ Ağ ] Internet hatti baslatiliyor..."
ifconfig eth0 10.0.2.15 netmask 255.255.255.0 up
route add default gw 10.0.2.2 eth0
echo "nameserver 8.8.8.8" > /etc/resolv.conf
echo "[ OK ] Internet hatti aktif!"

hostname -F /etc/hostname
exec /bin/sh
